server {
	listen 80;
	server_name _;

	root /usr/share/nginx/html;
	index index.html;

	# Rutas de Angular: si no existe el archivo, regresa index.html
	location / {
		try_files $uri $uri/ /index.html;
	}

	# Cache fuerte para assets con hash
	location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
		expires 1y;
		add_header Cache-Control "public, immutable";
		try_files $uri =404;
	}

	# No cachear el index para permitir despliegues sin problemas
	location = /index.html {
		expires -1;
		add_header Cache-Control "no-cache";
	}
}
